### ISSUE TITLE
Hints do not work

### ISSUE THREAD

**Issue by dragomano** [SychO9/smf-fa-board-icons#1]
![error](https://user-images.githubusercontent.com/229402/55544233-15d00f80-56e4-11e9-97b0-4ca0135bb97b.png)

**Comment by SychO9** [comment]
Oh I didn't notice, looks like I forgot to add a hook for the help admin txt

thanks for reporting this

**Comment by SychO9** [comment]
this commit fixes the issue https://github.com/SychO9/smf-fa-board-icons/commit/bf461597979c247cca49e940ca4e3dbee4b97137
